name: wagr_challenge
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: 4.3.2+3
  scrollable_positioned_list: 0.1.10
  intl: ^0.17.0
  confetti: ^0.5.4+1
  flare_flutter: any
  fluttertoast: ^8.0.3
  flutter_hooks: 0.15.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/response.json
    - assets/win.flr
    - assets/wagr_logo.jpg
